open-education-hub/operating-systems

.github/workflows/config/config.json, .github/workflows/rules/common/inlineTokenChildren.js, .github/workflows/rules/common/wordPattern.js, .github/workflows/rules/md101.js, .github/workflows/rules/md102.js, .github/workflows/rules/md103.js, .github/workflows/rules/md104.js, .github/workflows/rules/rules.js, .github/workflows/super-linter.yml
Use Super-Linter to validate code base. It will validate both code files (in different programming languages, quite a lot are supported) and Markdown files.
Markdown validation is configured in `config/config.json` and `rules/rules.js`.
Validation with Super-Linter is triggered for push actions and for pull requests.
=> Add Super-Linter as GitHub Action

.gitignore
Ignore swap files (.swo, .swp) and temporary editor files (*~).
=> .gitignore: Ignore temporary files

content/CPPLINT.cfg
Use `CPPLINT.cfg` in the `content/` folder to configure the use of `cpplint` as linter.
To test it, install `cpplint` as PIP package and run it against a file:
```
$ pip install cpplint
$ cpplint content/common/test/open.c
content/common/test/open.c:0:  No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
content/common/test/open.c:7:  Include the directory when naming header files  [build/include_subdir] [4]
content/common/test/open.c:8:  Include the directory when naming header files  [build/include_subdir] [4]
Done processing content/common/test/open.c
Total errors found: 3
```
A full list of configuration options is [here](https://github.com/cpplint/cpplint/blob/develop/cpplint.py#L287).
A sample extensive configuration file …
=> Add configuration file for cpplint

.github/workflows/.jscpd.json
Disable JSCPD validation (copy-paste detection). This tampers with SVG files.
=> .github: Disable JSCPD validation

.github/workflows/super-linter.yml, content/.clang-format
Disable clang-format from super-linter
To see how this works and the amounts of seemingly unconfigurable issues that appear:
1. Install [using `pip`](https://pypi.org/project/clang-format/). This installs a newer 14 version.
1. Dump the current configuration to get all (?) the configuration options:
```
clang-format -style=llvm -dump-config > current_clang-format
```
1. See [configuration options](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).
1. To emulate the `super-linter` behavior, run:
```
clang-format --dry-run -Werror chapters/data/lab/support/alloc-size/alloc_size.c
```
There are `-Wclang-format-violation` warnings that we weren't able to get rid of. We didn't find the [configuration options](https://clang.llvm.org/docs/ClangFormatStyleOptions.html). Some situations:
- …
=> Disable clang-format from super-linter

content/chapters/compute/lab/support/sum-array-bugs/seg-fault/Makefile, content/chapters/compute/lab/support/sum-array-bugs/seg-fault/sum_array_processes.d
This changes the following:
- the return type of `createSharedResultsArray()` to `long*` so no slicing is required and the function becomes more readable
- fully imports `core.sys.posix.sys.wait` to check the exit code modified by `waitpid()` more easily
- fixes the Makefile to compile both targets correctly
=> Simplify `compute/lab/support/sum-array-bugs/seg-fault/sum_array_processes.d`

content/chapters/compute/lab/support/apache2-simulator/apache2_simulator_condition.py
When creating threads, the wrong variable is given as an argument (sem instead of event), probably left over from the other program in this folder. All this fix does is change that variable.
=> Fix Thread init argument

content/chapters/compute/lab/support/race-condition/c/race_condition_tls.c
var variable shouldn't be initialized with `__thread` keyword since this is a task in the lab.
=> compute/lab: Fix initialization for var variable

content/chapters/compute/lab/content/copy-on-write.md
This command is misleading since pidof output might be empty and in this case the ps command will return the min_page and maj_page faults for the current bash process, even though fork_faults process exited.
=> compute/lab: Add -p argument to ps command

content/chapters/compute/lecture/demo/create-process/.gitignore, content/chapters/compute/lecture/demo/create-process/Makefile.linux, content/chapters/compute/lecture/demo/create-process/README.md, content/chapters/compute/lecture/demo/create-process/fork.c, content/chapters/compute/lecture/demo/create-process/multiple_forks.c
The lecture was missing a simple `fork()` demo. It jumped straight to `fork()` + `exec()`. A more granular introduction feels needed.
=> Improve process creation demos in the Compute lecture

content/common/makefile/defs.mk
This is annoying and doesn't make sense when you create program snippets that do not (yet) call functions. You end up with an error such as:
```
error: ... defined but not used [-Werror=unused-function]
```
There are probably other use cases.
=> common/makefile: Get rid of -Werror

content/CPPLINT.cfg, content/common/makefile/defs.mk, content/common/utils/log/CPPLINT.cfg, content/common/utils/utils.h
This changes the following:
- Allows lines up to 120 characters long in `CPPLINT.cfg`
- Changes makefile workflow to force users to include the directory of
"utils.h" or "log.h" like so: `#include "utils/utils.h"`
- Ignores `log.c` from cpplint because that code is taken from https://github.com/rxi/log.c
=> Update infrastructure to address cpplint errors

config.yaml
The first part of the I/O lab was added in https://github.com/open-education-hub/operating-systems/pull/30.
=> Add I/O lab to `config.yml`

content/chapters/io/lab/content/file-descriptors.md
The previous URL linked back to the file descriptors page, instead of file handlers.
=> io/lab: Fix file-descriptors.md link to handlers

.github/workflows/config/config.json
* Disable **MD004** to allow use of both `+` and `-` in lists mainly for quizzes
* Configure **MD035** to allow the use of `----`
* Disable **MD041** to allow files to start without a top-level header
=> workflows: Configure and disable Markdown linter options

content/chapters/io/lab/content/file-handlers.md
They now correctly reference `simple-file-operations/`.
=> Fix references to `simple-file-handling/` in the I/O lab

content/chapters/io/lab/content/remote-io.md
Fix typo for practice part of remote-io.
=> io/lab: Fix typo

content/common/makefile/slides.mk
Not using the flag results in shades of yellow, covering the content.
Signed-off-by: Alex Apostolescu <alexx.apostolescu@gmail.com>
=> `slides.mk`: Add '-vf format=yuv420p' flag to ffmpegAdd '-vf format=yuv420p' flag to ffmpeg

content/chapters/io/lab/content/io-internals.md, content/chapters/io/lab/solution/buffering/diy_buffering.c, content/chapters/io/lab/support/buffering/diy_buffering.c
lab/io: Fix diy_buffering and a typo
=> lab/io: Fix diy_buffering and a typo

content/chapters/io/lab/content/async-io.md
The time command given in the instructions for benchmarking the various implementations of a server tries to run "client_bench.sh" as if it were a command instead of an executable script, this PR fixes that.
=> io/lab: Fix time command

content/chapters/io/lecture/demo/devices/hwaddr-ioctl.c
Interface name in ```demo/devices/hwaddr-ioctl.c``` must be now sent as command line argument. (#65)
=> io/lecture: Pass interface name as CL argument

content/chapters/io/lecture/demo/devices/README.md
`demo/devices/filesystem-size.c` and `demo/devices/hwaddr-ioctl.c` were changed to get arguments from command line, so the `README.md` needed to be updated
=> io/lecture: Update README to match previous changes

content/chapters/software-stack/lab/solution/basic-syscall/arm/Makefile, content/chapters/software-stack/lab/solution/basic-syscall/arm/hello.s
This PR adds a `Makefile` rule that makes possible running `AArch64` binaries on `x86` machines and provides a hack for a `qemu` bug that introduces a SEGFAULT for the `bss` section. These two changes address the `Porting the initial program to ARM on 64 bits` task from arena.
Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>
=> software-stack/arena: Fix `AArch64` asm program SEGFAULT and add run rule

content/chapters/compute/lab/content/processes.md, content/chapters/compute/lab/solution/sleepy/sleepy_creator.py, content/chapters/compute/lab/support/sleepy/sleepy_creator.py
Support and solution files for `sleepy/sleepy_creator.py` demonstrate waiting for child processes by inducing the main process in a subsequent sleep.
A better demonstration of the concept of orphan processes and waiting for children is by explicitly making a call for the `wait` function.
This PR replaces the `sleep` call with `wait`, therefore providing a clearer demo of waiting, that would be continued further in the lab, in the `wait-for-me` and `fork` practice items.
Other solutions, for a more compact program would be:
```python
procs = [subprocess.Popen(["sleep", "1000"]) for _ in range(NUM_SLEEPS)]
list(map(lambda p: p.wait(), procs))
```
Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>
=> compute/lab: Replace `sleep` with `wait` call

content/chapters/compute/lab/content/benchmarks.md, content/chapters/compute/lab/content/processes-threads-apache2.md, content/chapters/compute/lab/content/processes.md, content/chapters/compute/lab/content/scheduling.md, content/chapters/compute/lab/content/synchronization.md
This PR fixes some minor typos from all over the lab text, adds backticks where needed and removes 2 ugly links from the start of the `scheduling` section. These links are introduced in the lab further down and become unnecessary right after the title.
Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>
=> compute/lab: Fix typos and remove redundant links

content/chapters/data/lab/content/investigate-memory.md, content/chapters/software-stack/lab/content/libcall-syscall.md, content/chapters/software-stack/lab/support/high-level-lang/Makefile, content/chapters/software-stack/lab/support/libcall-syscall/Makefile, content/common/makefile/single.mk
On some systems (such as the SO VM), `ltrace` results in empty outputs for binaries that otherwise make library calls. This is due to `now binding` and affects even system binaries, such as `ls` and `pwd`.
This PR forces the `lazy binding`, by modifying the `LDFLAGS` in Makefiles, and warns students about the potentially missing output for system executables.
Lab files that mention the `ltrace` function are:
```console
maria@ssshadows:~/Documents/school-work/git-stuff/operating-systems.git/content/chapters$ grep -nr "ltrace"
software-stack/lab/quiz/high-level-lang.md:9:- `ltrace`
software-stack/lab/quiz/libs.md:11:+ `ltrace`
software-stack/lab/quiz/libs.md:23:`ltrace` and `ldd` are used to capture connections to dynamic libraries.
software-stack/lab/content/app-investigate.md:45:1. Use …
```
=> {data,software-stack}/lab: Update `ltrace` usage

config.yaml
This PR changes the order of the chapters in Docusaurus to:
- Software Stack
- Data
- Compute
- I/O
- Application-Interaction
Fixes #121
=> Reorder chapter order

content/chapters/io/lab/content/file-descriptors.md
Explain the need for loops when using `read()` and `write()` and remove manual quotations.
=> io/lab: Explain the need for loops when using read/write

util/os-runner/Dockerfile, util/os-runner/Makefile, util/os-runner/README.md, util/os-runner/config_terminal.sh, util/os-runner/install-dmd.sh
Add Makefile for building and starting the `os-runner` container. `make run` can be used to start a new tty.
This solution does not support GUI applications or nested docker containers. The latter are to be run on the host machine as well.
Known issue:
- terminal overwrites line if the command is too long
=> util: Add docker environment to run labs

util/os-runner/install-dmd.sh
This also activates the compiler silently, without modifying the prompt.
=> util: Install `dmd` using the official installation script

content/chapters/software-stack/lab/content/introduction.md
Remove reference to deprecated `update-repo.sh` script which was removed in #116
=> software-stack/lab: Remove `update-repo.sh` reference

content/chapters/software-stack/lab/solution/basic-syscall/hello.asm, content/chapters/software-stack/lab/support/basic-syscall/hello.asm
In Intel syntax the destination operand is on the left-hand side.
=> software-stack/lab: Fix syntax for intel example

util/os-runner/Makefile
Force building an amd64 image using `buildx`. This is needed as `dlang/dmd` is not available for aarch64.
Makefile changes: tag the image, don't rebuild it if the hash hasn't changed, don't start another container if it's already running.
Tested on macOS and Windows (on Windows, if using Git Bash, you need either `alias docker='winpty docker'` or prefix the attach command as `winpty docker exec`).
=> util/os-runner: Switch to buildx. Improve Makefile

content/chapters/software-stack/lab/support/common-functions/Makefile
Replaced the `string.h` dependency with `printf.h`. Added all `.o` files and executables to the `clean` rule.
=> Makefile dependency & Clean all objects and execs

content/chapters/compute/lab/content/arena.md, content/chapters/compute/lab/content/processes.md, content/chapters/compute/lab/content/scheduling.md
There are broken GitHub links to other sections that currently give a `404` result. This PR fixes those links.
=> compute/lab: Fix links in content files

content/chapters/software-stack/lab/content/high-level-lang.md, util/os-runner/Dockerfile, util/os-runner/config_terminal.sh
Use `python3` when `ltrace`-ing or `strace`-ing if you have no python2 version installed. Otherwise, it will throw an error saying "strace: Can't stat 'python': No such file or directory".
=> Add python alternative for ltrace/strace 

content/misc/lab-setup.md
Fix for the alias section in [Setting up the Lab Environment](https://open-education-hub.github.io/operating-systems/Lab/Setting%20up%20the%20Lab%20Environment/lab-setup) not displaying the newlines properly.
=> lab-setup: Fix newlines between aliases

util/os-runner/install-dmd.sh
This changes the `--connect-timeout 5` parameter passed to `curl` in the script from https://dlang.org/install.sh. It increases it from 5 to 15 seconds. In some cases (on my machine for example, for reasons unknown) it takes about 6 seconds, causing the entire script to fail and therefore the docker build process as well.
=> Increase connect-timeout in dmd install script

util/os-runner/Dockerfile
This fixes #183 by using a newer version of `ltrace`. Since there's no newer version of `ltrace` available in `apt`, we have to compile it ourselves
=> Update ltrace version in os-runner docker image.

content/chapters/data/lab/content/investigate-memory.md, content/chapters/data/lab/content/working-memory.md, content/chapters/io/lecture/demo/devices/README.md, content/chapters/io/lecture/demo/optimizations/README.md, content/chapters/io/lecture/slides/IPC.md, content/chapters/io/lecture/slides/optimizations.md, content/chapters/software-stack/lab/content/app-investigate.md
Use `student@os` consistently as part of the prompt in code snippets.
=> Use `student@os` consistently as part of the prompt in code snippets

content/chapters/app-interact/lab/content/os-cloud.md, content/chapters/data/lab/content/process-memory.md, content/chapters/data/lab/content/working-memory.md, content/chapters/io/lab/content/arena.md, content/chapters/io/lab/content/file-mappings.md, content/chapters/io/lab/content/io-internals.md, content/chapters/io/lab/content/redirections.md, content/chapters/io/lab/content/remote-io.md, content/chapters/io/lab/quiz/mmap-read-write-benchmark.md, content/chapters/io/lab/quiz/pipe-ends.md, content/chapters/io/lecture/demo/IPC/README.md, content/chapters/io/lecture/demo/devices/README.md, content/chapters/io/lecture/demo/optimizations/README.md, content/chapters/io/lecture/slides/devices.md, content/chapters/io/lecture/slides/optimizations.md
Remove trailing white spaces in content files. This PR is built on top PR #177. I will rebase it once PR #177 is merged.
=> Fix trailing white spaces

content/chapters/data/lab/support/alloc-size/alloc_size.c
Changing ALLOC_SIZE_KB to 8 because there is no `brk()` call with this value.
When you start the program `./alloc_size` and investigate it with `pmap`, one can already notice that the heap has 132K already allocated.
```
~/Documents/operating-systems-work/content/chapters/data/lab/support/alloc-size (fix-alloc-size-kb-value ✗) pmap $(pidof alloc_size)
13764:   ./alloc_size
000055eede2e6000      4K r---- alloc_size
000055eede2e7000      4K r-x-- alloc_size
000055eede2e8000      4K r---- alloc_size
000055eede2e9000      4K r---- alloc_size
000055eede2ea000      4K rw--- alloc_size
000055eedfd7b000    132K rw---   [ anon ]
00007f6445ed9000    136K r---- libc-2.31.so
00007f6445efb000   1504K r-x-- libc-2.31.so
```
Because NUM_STEPS * ALLOC_SIZE_KB < initial heap size, there is going to be no …
=> Set ALLOC_SIZE_KB value to 64

.github/workflows/super-linter.yml
Some shell scripts may just be included (`source`) in other shell scripts and don't require execution permission.
=> .github/workflows: Disable checking of executable bit on shell scripts

util/os-runner/Makefile, util/os-runner/README.md
Add help menu to the `os-runner` Makefile.
=> util/os-runner: Add colored help menu to makefile

.github/scripts/add-labels.js
The `add-labels.js` script was wrongly assigning the label `kind/improvement` instead of `kind/improve`. This fixes the issue.
Fixes #236.
=> infra/labeler: Change `kind/improvement` to `kind/improve`

content/chapters/compute/lecture/slides/processes.md
The demo was referring to process, not thread attributes.
Fixes #233.
=> compute/lecture: Fix typo from `thread` to `process`

content/chapters/data/lab/content/investigate-memory.md
After installing `libjemalloc-dev`, `/usr/lib/x86_64-linux-gnu/libjemalloc.so.1` is not created.
Hence, when running the commands from the lab, I am getting the following error:
```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1 /bin/ps
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libjemalloc.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
I am changing the contents of the lab to use `/usr/lib/x86_64-linux-gnu/libjemalloc.so` which is a symbolic link that will always point to the correct version of the library (in this specific case it's `libjemalloc.so.2`.
=> Fix path to `jemalloc` library

content/chapters/data/lab/content/process-memory.md, content/common/makefile/defs.mk, content/common/makefile/single.mk
Add an indication to configure LDFLAGS to create a static executable.
Also, move LDFLAGS to `defs.mk`.
=> Add an indication to build a static executable

util/super-linter.sh
Add "-i" flag to start the super-linter container in interactive mode, with bash as entrypoint.
=> util/super-linter: Add interactive option

content/assignments/memory-allocator/README.md
The checker uses the size field from struct block_meta and assumes it contains the aligned size of the payload.
Add this information to the assignment statement.
=> asg/mem-alloc: Restrictions on size field

CPPLINT.cfg
This filter forces all `TODO`s to be formatted like so `TODO(someone or a bug): ...`. This does not match our `TODO`s, which indicate code that students must fill in.
=> config: Remove `readability/todo` filter from `cpplint`

content/chapters/data/lab/content/process-memory.md, content/chapters/data/lab/support/copy/benchmark_cp.sh
Added a note in the `benchmark_cp.sh` script to warn the users to run the script from local environment.
The Docker container does not have permission to write to `/proc/sys/vm/drop_caches`.
This PR resolves #261.
Signed-off-by: Iulian Tăiatu <iulian27_marius@yahoo.com>
=> data/lab: Add warning about running `benchmark_cp.sh`

content/chapters/compute/lab/content/synchronization.md, content/chapters/compute/lab/support/apache2-simulator/apache2_simulator_condition.py
Replace `with event:` with the equivalent `acquire() and `release()` calls.
Closes #131
=> compute/lab: Remove `with event`

content/chapters/compute/lab/content/arena.md, content/chapters/compute/lab/content/copy-on-write.md, content/chapters/compute/lab/support/page-faults/.gitignore, content/chapters/compute/lab/support/page-faults/Makefile, content/chapters/compute/lab/support/page-faults/page_faults.c
To force a major page fault, I/O reads are forced. Getting swap-ins and outs would be another way, but it is more difficult.
Closes #129
=> compute/lab: Add minor and major page fault task

CPPLINT.cfg
Remove the check for directory name in include directives from `cpplint`.
=> `infra/cpplint`: Disable `include_subdir`

content/chapters/compute/lab/support/mini-shell/mini_shell.c
Hello,
I noticed that the `mini-shell.c` file used in the Arena subchapter of the Compute section had an issue regarding the calls to `strtok_r` used to parse input from the user which caused it to not compile. The calls only used 2 arguments, as if it was `strtok` which was called. I added the third parameter, `&saveptr`, in order to properly call `strtok_r`.
=> `compute/lab`: Added third argument for strtok_r in mini-shell.c

content/assignments/mini-libc/src/io/read_write.c
=> assignments/mini-libc: Use `errno` in implementation of `write()` and `read()`

content/assignments/mini-libc/src/string/string.c
Remove spacing between `TODO` comments and existing code. This is for consistency throughout the assignment skeleton.
=> `asgn/mini-libc`: Use consistent spacing for TODOs

.github/workflows/actions.yml, .github/workflows/deployment.yml, .github/workflows/os-runner.yml
The default branch of the repository was changed from `master` to `main`. Use `main` branch instead of `master` branch in all GitHub workflows.
=> workflows: Use main branch

content/assignments/minishell/src/Makefile
Improve the `Makefile` used to build the source code. Improve layout, indentation and spacing. Add configurable variables for build commands.
=> `asg/minishell`: Improve source code Makefile

content/assignments/mini-libc/tests/run_all_tests.sh
The `tests/run_all_tests.sh` script uses the `en_US.UTF-8` locale. This may not be available on certain systems, requiring installation. Replace it with the use of the generally available `C` locale.
=> `asg/mini-libc/tests`: Use available locale `LC_ALL=C`

content/assignments/mini-libc/src/stat/fstat.c, content/assignments/mini-libc/src/stat/stat.c
Reference solution for implementing `stat()` and `fstat()` relies on system call being made. Include `internal/syscall.h` in corresponding source code files to provide the `syscall()` function.
=> `asg/mini-libc`: Include `internal/syscall.h` in stat files

content/assignments/mini-libc/tests/Makefile
Use the absolute path of `SRC_PATH` in `tests/Makefile` rather than prepending `../` when changing the directory.
=> asg/mini-libc: Use absolute path for SRC_PATH

.github/workflows/pr-deployment.yml
The action builds the rendered website and pushes it to the `gh-pages` in a directory named after the PR number: `refs/pull/<number>/merge`. It then publishes a message containing the link where the website may be inspected.
I tested the action here: https://github.com/teodutu/operating-systems/pull/8#issuecomment-1739160737
=> workflows: Add PR deployment action

.github/workflows/pr-deployment.yml
Fix PR deployment action by use the head_ref for checkout action in order to grab the PR base branch.
=> workflows: Fix PR deployment action

.github/labeler.yml, README.md
PR #317 restructured the repository. A part of its changes meant removing the `chapters` directory. This commit fixes #340 by removing mentions to it from the `README.md` and from the labeler action.
=> Propagate changes to the repo's layout to the `README.md` and labeler action

.github/pull.yml
This `pull.yml` file is the base file for the cs-pub-ro / open-education-hub synchronization. Related to #338
=> Add basic .yml file for cs-pub-ro -> oeh sync
