open-education-hub/operating-systems

.github/workflows/rules/md101.js

There was a missing comma at the end for keywords.

.github: Fix md101.js syntax

---

util/update-repo.sh

Add script to update repository.

util: Add script to update repository

---

content/chapters/compute/lab/content/synchronization.md
content/chapters/compute/lab/solution/race-condition/d/race_condition_atomic.d
content/chapters/compute/lab/support/race-condition/d/race_condition_atomic.d

This solves https://github.com/open-education-hub/operating-systems/issues/33.

Improve atomic assembly explanation in the Compute lab

---

content/chapters/io/lab/content/file-handlers.md

lab/io: Fix output from java file in `simple-file-operations/`

---

content/chapters/io/lab/content/pipes.md
content/chapters/io/lab/solution/pipes/anonymous_pipe.c
content/chapters/io/lab/support/pipes/anonymous_pipe.c
content/chapters/io/lab/support/redirect/.gitignore

General improvements.
cc: @teodutu

General improvements

---

config.yaml

The sections were added in https://github.com/open-education-hub/operating-systems/pull/55.

Add "Remote I/O" subsections to `config.yaml`

---

content/chapters/io/lab/solution/receive-challenges/receive_net_dgram_socket.c

lab/io: Remove unnecessary variables

---

config.yaml

io/lab: Fix config sidebar

---

config.yaml

`config.yaml`: Fix data lab configuration

---

config.yaml

config: Solve a typo

---

content/chapters/io/lecture/demo/IPC/datagram_socket_server.c
content/chapters/io/lecture/demo/IPC/stream_socket_server.c
content/chapters/io/lecture/demo/IPC/unix_socket_server.c

Made all servers in ```demo/IPC``` run using while(1) loop ( #66 ) 
I would also add the feature to get the port, which the server starts on, from the command line. 

io/lecture: Make servers in demo/IPC run in a loop

---

content/chapters/io/lecture/demo/devices/filesystem-size.c

io/lecture: Pass partition name as command line argument

---

.checkpatch.conf
.github/workflows/checkpatch.yml

Fixes #68
Might need further changes since this is the default version of `checkpatch.pl` and it doesn't verify only the source codes.
I will look more into it, but this is the starting point.

workflows: Add checkpatch.pl

---

content/chapters/app-interact/lab/support/so-cloud/so-cloud/vm.py

- Remove solution from support folder
- Add TODOs for vm_stop function

app-interact/lab: Update vm_stop function

---

config.yaml

Add configuration for `app-interact` lecture.

config.yaml: Configure app-interact lecture

---

config.yaml

config.yaml: Fix typo in `Application-Interaction` slides path

---

content/chapters/software-stack/lab/content/basic-syscall.md

Add a paragraph to explain the `write()` syscall. Briefly mention file descriptors.

software-stack/lab: Explain the write() system call

---

.github/scripts/add-labels.js
.github/workflows/labeler.yml

- Change labeller action interval from 5 mintes to 1 day
- Change kind labeller script to iterate over all PRs before adding labels

infra/labeler: Fix labeller interval and script

---

content/chapters/io/lab/content/pipes.md
content/chapters/io/lab/solution/pipes/.gitignore
content/chapters/io/lab/solution/pipes/Makefile
content/chapters/io/lab/solution/pipes/anonymous_pipe.c
content/chapters/io/lab/support/pipes/anonymous_pipe.c

Summary:
- Add sample output
- Replace `scanf` with `fgets`
- Add `Makefile` and `.gitignore` to solution folder

io/lab: Update now we pipe

---

content/chapters/software-stack/lab/content/modern-sw-stack.md

Software Stack lab - Fix image link

---

content/chapters/software-stack/lab/support/basic-syscall/hello.asm
content/chapters/software-stack/lab/support/basic-syscall/hello.s

Signed-off-by: Teodor Juravlea <teodorjuravlea@gmail.com>

lab/software-stack: Fix typo

---

content/chapters/software-stack/lab/content/app-investigate.md
content/chapters/software-stack/lab/content/arena.md
content/chapters/software-stack/lab/content/basic-syscall.md
content/chapters/software-stack/lab/content/high-level-lang.md
content/chapters/software-stack/lab/content/libc.md
content/chapters/software-stack/lab/content/libcall-syscall.md
content/chapters/software-stack/lab/content/modern-sw-stack.md
content/chapters/software-stack/lab/content/static-dynamic.md
content/chapters/software-stack/lab/content/syscall-wrapper.md

Signed-off-by: Teodor Juravlea <teodorjuravlea@gmail.com>

lab/software-stack: Fix typos and grammar errors

---

util/os-runner/README.md

I wrote this from online docs but did not test it yet. If anyone can test or update this, it would be great.

util/os-runner: Update documentation

---

content/chapters/software-stack/lab/content/libc.md
content/chapters/software-stack/lab/solution/libc/memory.c
content/chapters/software-stack/lab/support/libc/memory.c
content/chapters/software-stack/lab/support/libc/vendetta.c

Fix issue #174 and other items related to the Libc section in the Software Stack lab.

`software-stack/lab`: Fix issue #174

---

content/chapters/data/lab/content/investigate-memory.md
content/chapters/data/lab/content/memory-support.md
content/chapters/data/lab/content/overview.md
content/chapters/data/lab/content/process-memory.md
content/chapters/data/lab/content/working-memory.md
content/chapters/software-stack/lab/content/introduction.md

Signed-off-by: Teodor Juravlea <teodorjuravlea@gmail.com>

lab: Fix typos and punctuation

---

assignments/async-web-server/README.md
assignments/memory-allocator/README.md
assignments/mini-libc/README.md
assignments/minishell/README.md
assignments/parallel-graph/README.md
config.yaml

Due to https://github.com/open-education-hub/operating-systems/issues/102, I can't check if the website works correctly on my machine. If any of you can, please do so and tell me if I did anything stupid.

Add `assignments/` folder skeleton

---

.github/workflows/os-runner.yml
util/os-runner/Makefile
util/os-runner/install-dmd.sh

util/os-runner: Add pipeline to publish os-runner image

---

content/chapters/data/lab/content/process-memory.md
content/chapters/data/lab/quiz/memory-granularity.md

Fixes #207.
The quiz was previously removed by #203, but I think it can be revived.

data/lab: Reintroduce "Memory Granularity" quiz

---

.github/checkpatch.conf

Ignore warnings that are not relevant for the content.

Update configuration for checkpatch

---

.github/labeler.yml
.github/scripts/add-labels.js
.github/workflows/labeler.yml

- Switch to another GitHub action since the other didn't work with crontab / pull_request
- Update configuration file
- Fix add-labels script

infra/labeler: Fix pull request labeler workflow

---

config.yaml
content/chapters/compute/lab/content/hardware-perspective.md
content/chapters/compute/lab/content/overview.md

compute/lab: Rename `Benchmarks` section

---

content/chapters/compute/lecture/slides/notifications.md

lectures/compute: Add mention about `notify`

---

content/chapters/compute/lab/content/threads.md

[lab/compute]: Add threads vs processes table, plus some explanations

---

content/assignments/minishell/util/.gitignore
content/assignments/minishell/util/parser/CUseParser.c
content/assignments/minishell/util/parser/DisplayStructure.cpp
content/assignments/minishell/util/parser/Makefile
content/assignments/minishell/util/parser/README.md
content/assignments/minishell/util/parser/UseParser.cpp
content/assignments/minishell/util/parser/parser.h
content/assignments/minishell/util/parser/parser.l
content/assignments/minishell/util/parser/parser.y
content/assignments/minishell/util/parser/tests/negative_tests.txt
content/assignments/minishell/util/parser/tests/small_tests.txt
content/assignments/minishell/util/parser/tests/ugly_tests.txt

assignment/minishell: Add parser for minishell assignment

---

config.yaml

Fixes an issue with some files not being copied and causing the build process to error

infra: Fix build error introduced by #262

---

content/chapters/compute/lab/content/synchronization.md

compute/lab: Add spurious wakeup explanation

---

content/chapters/io/lab/content/beyond-network-sockets.md

Stating the obvious won't hurt.
Closes #137.

io/lab: Explain UNIX sockets

---

content/chapters/io/lab/content/file-mappings.md

Include a section that explores the advantages of loading dynamic libraries using `mmap()`, rather than `read()`.
The main arguments are `demand paging` and convenience.
Closes https://github.com/open-education-hub/operating-systems/issues/138.

io/lab: Explain the use of `mmap()` in loading dynamic libraries

---

config.yaml
content/chapters/compute/lab/content/overview.md
content/chapters/compute/lab/content/user-level-threads.md
content/chapters/compute/lab/quiz/fiber-strace.md
content/chapters/compute/lab/quiz/sleeping-on-a-fiber.md
content/chapters/compute/lab/support/user-level-threads/.gitignore
content/chapters/compute/lab/support/user-level-threads/CMakeLists.txt
content/chapters/compute/lab/support/user-level-threads/CPPLINT.cfg
content/chapters/compute/lab/support/user-level-threads/simple.cc
content/chapters/compute/lab/support/user-level-threads/sum.cc
content/chapters/compute/lab/support/user-level-threads/threads_and_fibers.cc
content/chapters/compute/lab/support/user-level-threads/yield_barrier.cc
content/chapters/compute/lab/support/user-level-threads/yield_launch.cc

compute/lab: Add user-level threads section

---

assignments/minishell/README.md

I have created and translated the statement of the minishell assignment.
Waiting to merge #110 before merging this.

Add `minishell` assignment statement

---

content/assignments/minishell/checker/.gitignore
content/assignments/minishell/checker/_test/inputs/test_01.txt
content/assignments/minishell/checker/_test/inputs/test_02.txt
content/assignments/minishell/checker/_test/inputs/test_03.txt
content/assignments/minishell/checker/_test/inputs/test_04.txt
content/assignments/minishell/checker/_test/inputs/test_05.txt
content/assignments/minishell/checker/_test/inputs/test_06.txt
content/assignments/minishell/checker/_test/inputs/test_07.txt
content/assignments/minishell/checker/_test/inputs/test_08.txt
content/assignments/minishell/checker/_test/inputs/test_09.txt
content/assignments/minishell/checker/_test/inputs/test_10.txt
content/assignments/minishell/checker/_test/inputs/test_11.txt
content/assignments/minishell/checker/_test/inputs/test_12.txt
content/assignments/minishell/checker/_test/inputs/test_13.txt
content/assignments/minishell/checker/_test/inputs/test_14.txt
content/assignments/minishell/checker/_test/inputs/test_15.txt
content/assignments/minishell/checker/_test/inputs/test_16.txt
content/assignments/minishell/checker/_test/inputs/test_17.txt
content/assignments/minishell/checker/_test/inputs/test_18.txt
content/assignments/minishell/checker/_test/refs/test_18.ref
content/assignments/minishell/checker/_test/run_test.sh
content/assignments/minishell/checker/_test/test_lib.sh
content/assignments/minishell/checker/run_all.sh

Add minishell checker

---

content/assignments/minishell/src/Makefile
content/assignments/minishell/src/cmd.c
content/assignments/minishell/src/cmd.h
content/assignments/minishell/src/main.c
content/assignments/minishell/src/utils.c
content/assignments/minishell/src/utils.h

assignment/minishell: Add src for minishell

---

content/chapters/compute/lab/content/user-level-threads.md
content/chapters/compute/lab/support/user-level-threads/CMakeLists.txt
util/os-runner/Dockerfile

{infra/os-runner, compute/lab}: Fix docker and add explicit prerequisites to `User-Level Threads`

---

content/chapters/data/lab/content/investigate-memory.md
content/chapters/io/lab/content/remote-io.md

{io,data}/lab: Fix broken links

---

content/chapters/io/lab/content/async-io.md
content/chapters/io/lab/content/beyond-network-sockets.md
content/chapters/io/lab/content/client-server-model.md
content/chapters/io/lab/content/io-internals.md
content/chapters/io/lab/content/local-io-in-action.md
content/chapters/io/lab/content/networking-101.md
content/chapters/io/lab/content/pipes.md
content/chapters/io/lab/content/redirections.md
content/chapters/io/lab/content/remote-io.md
content/chapters/io/lab/quiz/fewer-than-2-copies.md

io/lab: Fix typos

---

.github/workflows/actions.yml
.github/workflows/labeler.yml

Update workflows to load GH Actions from global repository

task: Update workflows to load GH Actions from global repository

---

content/assignments/minishell/README.md

Those are pointless bonus tasks on top of the fact that _they aren't graded_.

asg/minishell: Remove bonus

---

content/data/lab/content/working-memory.md

Updated comment to reflect actual content in code.

data: Fix typo in working-memory.md

---

landing-page/README.md

Add contents to landing page. Add content description and summary of chapters.

landing-page: Fill landing page
